# Generated by Django 4.0.6 on 2022-08-01 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_currency_customer_address_customer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_issued',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_and_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_and_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_and_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 18, 41, 42, 410117), null=True),
        ),
    ]
