# Generated by Django 4.0.6 on 2022-09-02 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_accountr_name_account_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
