# Generated by Django 4.0.6 on 2022-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_card_date_issued_alter_loan_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
